<html><head></head><body>

<table id="contenttable" style="background-color: #ffffff; text-align: center !important; border-style: none; width: 100% !important; max-width: 600px !important; margin: 0 !important !important auto !important !important;" cellspacing="0" cellpadding="0" border="0" align="center"><tbody><tr><td style="font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" width="100%"><table width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#FFFFFF"><tbody><tr><td style="text-align: center; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse; padding: 0px;" class="mceEditable" width="100%" bgcolor="#222222">
<p style="font-family: 'Droid Serif', Georgia, Times, 'Times New Roman', serif; text-align: center; color: #ffffff; font-size: 30px; line-height: 140%;;margin:30px 0px;padding:0px;color:rgb(255, 255, 255);font-style:normal;font-size:30px;font-family:'Droid Serif', Georgia, Times, 'Times New Roman', serif;font-weight:400;line-height:42px;text-decoration:none solid rgb(255, 255, 255);text-transform:none;display:block;text-align:center"><center><img src="https://www.scorepositivo.com.br/static/images/seresa-logo.png" alt="Boa vista SCPC" style="display: block; height: auto; line-height: 100%; border-width: 0; outline-style: none; text-decoration: none;;margin:0px;float:none;aligner:center;" width="141"></center></p></td></tr></tbody></table><table class="corpo textoNewsletter" style="font-size: 18px !important;" width="100%" cellspacing="0" cellpadding="25" border="0" bgcolor="#FFFFFF"><tbody><tr>
<td style="text-align: left; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" class="mceEditable" width="100%" bgcolor="#ffffff"><p style="margin:18px 0px 20px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:18px;font-family:'Droid Serif', serif;font-weight:400;line-height:25.2px;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left">Caro leitor,&nbsp;</p>
<p style="margin:18px 0px 20px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:18px;font-family:'Droid Serif', serif;font-weight:400;line-height:25.2px;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left">Você está recebendo em primeira mão o acesso ao documento prioritário:<span>&nbsp;</span><strong>O Próximo Case Histórico de Ganhos.</strong></p>
<p style="margin:18px 0px 20px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:18px;font-family:'Droid Serif', serif;font-weight:400;line-height:25.2px;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left">Qual será a próxima&nbsp;<strong><u>valorização explosiva</u></strong>&nbsp;no mundo das criptomoedas.</p>
<p style="margin:18px 0px 20px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:18px;font-family:'Droid Serif', serif;font-weight:400;line-height:25.2px;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left"><font color="#FF0000"><strong>575 vezes nos próximos meses!</strong></font></p>


<p style="margin:18px 0px 20px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:18px;font-family:'Droid Serif', serif;font-weight:400;line-height:25.2px;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left"><strong>Mas atenção: é de extrema importância que você não deixe para ver isso depois. Não quero que perca o&nbsp;<em>momentum</em>&nbsp;e abra mão de parte dos ganhos que estão em jogo.</strong></p><div style="margin:0px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:11px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:400;line-height:normal;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left">
<div style="text-align: center;;margin:0px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:11px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:400;line-height:normal;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:center">
<a class="callToActionButton" href="https://www.scorepositivo.com.br/44751481878488.pdf" style="border-bottom: 3px solid #8f031f; background-color: #cc0033; border-radius: 5px; color: #ffffff; padding: 12px 30px; display: inline-block; font-family: Calibri, sans-serif; font-size: 22px; font-weight: bold; text-transform: uppercase; line-height: 28px; text-align: center; text-decoration: none; -webkit-text-size-adjust: none; mso-hide: all;;margin:0px;padding:12px 30px;color:rgb(255, 255, 255);font-style:normal;font-size:22px;font-family:'Droid Serif', serif;font-weight:700;line-height:28px;text-decoration:none solid rgb(255, 255, 255);text-transform:uppercase;display:inline-block;text-align:center" rel="noopener noreferrer">ACESSE O DOCUMENTO</a></div></div>
<p style="margin:18px 0px 20px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:18px;font-family:'Droid Serif', serif;font-weight:400;line-height:25.2px;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left">Um abraço,</p><p style="margin:18px 0px 20px;padding:0px;color:rgb(34, 34, 34);font-style:normal;font-size:18px;font-family:'Droid Serif', serif;font-weight:400;line-height:25.2px;text-decoration:none solid rgb(34, 34, 34);text-transform:none;display:block;text-align:left">André Franco.</p>
</td></tr></tbody></table><table class="corpo textoNewsletter" style="font-size: 18px !important;" width="100%" cellspacing="0" cellpadding="25" border="0" bgcolor="#FFFFFF"><tbody><tr><td style="text-align: center; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" class="mceEditable" width="100%" bgcolor="#ffffff" align="center">
<img src="https://image.ibb.co/mAGSsf/unnamed.png#https://image.ibb.co/mAGSsf/unnamed.png" alt="" style="margin:0px;float:none" width="100%"></td></tr></tbody></table><table class="linksFooter texto-rodape" width="100%" cellspacing="0" cellpadding="20" border="0" bgcolor="#211f23"><tbody><tr><td style="text-align: center; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;"><table width="100%"><tbody><tr>
<td style="text-align: center; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;"><table style="margin: 0 auto 0 auto;" width="50%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" width="41">
<a href="#: relative;;margin:0px;padding:0px;color:rgb(195, 29, 79);font-style:normal;font-size:13px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:600;line-height:normal;text-decoration:none solid rgb(195, 29, 79);text-transform:none;display:inline;text-align:center" rel="noopener noreferrer"><img src="https://empiricusimagens.s3.amazonaws.com/imagens/novo-layout-newsletters/ico-sociais_01.jpg" alt="Facebook" style="display: block; border-width: 0; height: auto; line-height: 100%; outline-style: none; text-decoration: none;;margin:0px;float:none" width="41" height="42"></a></td>
<td style="font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" width="41"><a href="#" title="Twitter" style="white-space: nowrap; color: #c31d4f !important; text-decoration: none; font-weight: 600; font-size: 13px; position: relative;;margin:0px;padding:0px;color:rgb(195, 29, 79);font-style:normal;font-size:13px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:600;line-height:normal;text-decoration:none solid rgb(195, 29, 79);text-transform:none;display:inline;text-align:center" rel="noopener noreferrer">
<img src="https://empiricusimagens.s3.amazonaws.com/imagens/novo-layout-newsletters/ico-sociais_02.jpg" alt="Twitter" style="display: block; border-width: 0; height: auto; line-height: 100%; outline-style: none; text-decoration: none;;margin:0px;float:none" width="41" height="42"></a></td><td style="font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" width="41">
<a href="#" title="Youtube" style="white-space: nowrap; color: #c31d4f !important; text-decoration: none; font-weight: 600; font-size: 13px; position: relative;;margin:0px;padding:0px;color:rgb(195, 29, 79);font-style:normal;font-size:13px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:600;line-height:normal;text-decoration:none solid rgb(195, 29, 79);text-transform:none;display:inline;text-align:center" rel="noopener noreferrer"><img src="https://empiricusimagens.s3.amazonaws.com/imagens/novo-layout-newsletters/ico-sociais_04.jpg" alt="Youtube" style="display: block; border-width: 0; height: auto; line-height: 100%; outline-style: none; text-decoration: none;;margin:0px;float:none" width="41" height="42"></a></td>
<td style="font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" width="41"><a title="Google+" style="white-space: nowrap; color: #c31d4f !important; text-decoration: none; font-weight: 600; font-size: 13px; position: relative;;margin:0px;padding:0px;color:rgb(195, 29, 79);font-style:normal;font-size:13px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:600;line-height:normal;text-decoration:none solid rgb(195, 29, 79);text-transform:none;display:inline;text-align:center">
<img src="https://empiricusimagens.s3.amazonaws.com/imagens/novo-layout-newsletters/ico-sociais_05.jpg" alt="Google+" style="display: block; border-width: 0; height: auto; line-height: 100%; outline-style: none; text-decoration: none;;margin:0px;float:none" width="41" height="42"></a></td><td style="font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" width="41">
<a href="#" title="Linkedin" style="white-space: nowrap; color: #c31d4f !important; text-decoration: none; font-weight: 600; font-size: 13px; position: relative;;margin:0px;padding:0px;color:rgb(195, 29, 79);font-style:normal;font-size:13px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:600;line-height:normal;text-decoration:none solid rgb(195, 29, 79);text-transform:none;display:inline;text-align:center" rel="noopener noreferrer"><img src="https://empiricusimagens.s3.amazonaws.com/imagens/novo-layout-newsletters/ico-sociais_06.jpg" alt="Facebook" style="display: block; border-width: 0; height: auto; line-height: 100%; outline-style: none; text-decoration: none;;margin:0px;float:none" width="41" height="42"></a></td></tr></tbody></table></td></tr><tr>
<td style="font-size: 15px; color: #ffffff; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;"><p style="text-align: center; font-family: 'Lato', Helvetica, Arial, sans-serif !important; color: #ffffff; margin: 20px 0 1em 0;;margin:20px 0px 15px;padding:0px;color:rgb(255, 255, 255);font-style:normal;font-size:15px;font-family:Lato, Helvetica, Arial, sans-serif;font-weight:400;line-height:normal;text-decoration:none solid rgb(255, 255, 255);text-transform:none;display:block;text-align:center">Av. Brigadeiro Faria Lima, 3.477 - Torre B - 10º Andar <br> CEP 04538-133 - Itaim Bibi - São Paulo</p></td></tr><tr>
<td style="padding-top: 20px; padding-bottom: 20px; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;" valign="middle" align="center"><img src="https://www.scorepositivo.com.br/static/images/seresa-logo.png" alt="Boa vista SCPC" style="display: block; height: auto; line-height: 100%; border-width: 0; outline-style: none; text-decoration: none;;margin:0px;float:none" width="141"></td></tr><tr><td style="font-size: 14px; color: #999999; text-align: center; font-family: 'Lato', Helvetica, Arial, sans-serif !important; border-collapse: collapse;">
</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></body></html>